 platform :ios, '10.0'

target 'ExampleFW' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleFW
 pod 'RoundAddButton', :path => '../RoundAddButton'

end
